package com.almightyvats.sensorsafe.model.custom;

public enum SanityCheckType {
    NO_ERROR("NO_ERROR"),
    READING_TOO_HIGH("READING_TOO_HIGH"),
    READING_TOO_LOW("READING_TOO_LOW"),
    READING_NAN("READING_NAN"),
    READING_DUPLICATE("READING_DUPLICATE"),
    READING_BELOW_VAR_COFF("READING_BELOW_VAR_COFF"),
    READING_ABOVE_RATE_OF_CHANGE("READING_ABOVE_RATE_OF_CHANGE"),
    READING_LOWER_FOR_SOLAR_ELEVATION("READING_LOWER_FOR_SOLAR_ELEVATION"),
    READING_NOT_ZERO_FOR_SOLAR_ELEVATION("READING_NOT_ZERO_FOR_SOLAR_ELEVATION"),
    READING_INVALID_VALUE("READING_INVALID_VALUE"),
    READING_INVALID_TIMESTAMP("READING_INVALID_TIMESTAMP"),
    READING_INVALID_SENSOR_ID("READING_INVALID_SENSOR_ID"),
    READING_INVALID_SENSOR_TYPE("READING_INVALID_SENSOR_TYPE");

    SanityCheckType(String reading_type) {
    }
}
